shader_type canvas_item;

uniform vec4 line_color : source_color = vec4(1.0, 1.0, 1.0, 1.0);
uniform float outline_width : hint_range(0.0, 10.0) = 0.0; 

const vec2 OFFSETS[8] = {
    vec2(-1, -1), vec2(-1, 0), vec2(-1, 1), vec2(0, -1), vec2(0, 1), 
    vec2(1, -1), vec2(1, 0), vec2(1, 1)
};

void fragment() {
    vec4 color = texture(TEXTURE, UV);
    
    if (outline_width > 0.0) {
        vec2 size = TEXTURE_PIXEL_SIZE * outline_width;
        float outline = 0.0;
        
        for (int i = 0; i < OFFSETS.length(); i++) {
            outline += texture(TEXTURE, UV + size * OFFSETS[i]).a;
        }
        outline = min(outline, 1.0);
        
        COLOR = mix(color, line_color, outline - color.a);
    } else {
        COLOR = color;
    }
}